---
output: 
  pdf_document:
    #citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: ~/Dropbox/Uni/Misc/template.tex
title: "ChangeMyView: How Moral Appeals Induce Persuasion"
#thanks: "Replication files are available on the author's Github account (http://github.com/pwkraft). **Current version**: `r format(Sys.time(), '%B %d, %Y')`; **Corresponding author**: patrick.kraft@stonybrook.edu."
author:
- name: Patrick W. Kraft
  affiliation: Stony Brook University
abstract: "Overview of initial results"
keywords: "Moral Foundations, Persuasion, Attitude Change"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
# spacing: double
# bibliography: ~/Dropbox/master.bib
# biblio-style: apsr
endnote: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = TRUE,fig.height=3, fig.width=6)
```

# Introduction

# Description of Dataset
```{r}
library(tidyr)
library(dplyr)
library(purrr)
library(ggplot2)
library(quanteda)

## load data
load("out/cmv_data.Rdata")
```

```{r}
## load dictionary
dict <- dictionary(file="in/moral foundations dictionary.dic", format="LIWC")

## create corpus $ dfm for positive posts
countMFT <- function(x, dic){
  corpus <- corpus(x)
  txt <- dfm(corpus, dictionary = dic)
  data <- (data.frame(txt)/ntoken(corpus)) %>% 
    mutate(Harm = HarmVirtue + HarmVice,
           Fairness = FairnessVirtue + FairnessVice,
           Ingroup = IngroupVirtue + IngroupVice,
           Authority = AuthorityVirtue + AuthorityVice,
           Purity = PurityVirtue + PurityVice,
           MFTcombined = Harm + Fairness + Ingroup + Authority + Purity) %>%
    select(-HarmVirtue:-PurityVice)
  data
}
```

*ToDos*
=========
- clean original posts (links etc)!
- adjust confidence intervals to correct for multiple comparisons
-  add more comments in functions!


# Moral Foundations and Persuadability

```{r}
###################
### Examine OP data
###################

mft_op <- data_op[,c("title","text")] %>% 
  apply(1, paste, collapse=" ") %>%
  countMFT(dict) %>% bind_cols(data_op) %>% as_tibble()

plot_df <- mft_op %>%
  select(-name:-text, -MFTcombined) %>%
  gather(key=foundation, value=proportion,-Delta) %>%
  mutate(foundation = factor(foundation, levels = rev(c("Authority", "Ingroup", "Purity"
                                                        , "Fairness", "Harm", "MoralityGeneral"))
                             , labels = rev(c("Authority", "Ingroup", "Purity"
                                              , "Fairness", "Harm", "General\nMorality")))) %>%
  group_by(foundation,Delta) %>%
  summarise(mean = mean(proportion), sd = sd(proportion), n = n()) %>%
  mutate(se = sd/sqrt(n), cilo = mean - se, cihi = mean + se)

ggplot(plot_df, aes(y=foundation, x=mean, xmin=cilo, xmax=cihi, col=Delta, shape=Delta)) + 
  theme_classic() + theme(panel.border = element_rect(fill=NA)) + 
  geom_point(position = position_nudge(y=-.1+.2*plot_df$Delta)) + 
  geom_errorbarh(height=0, position = position_nudge(y=-.1+.2*plot_df$Delta)) + 
  ylab("Moral Foundation") + xlab("Proportion of Dictionary Terms") +
  ggtitle("Moral Foundations and Persuadability")
```


# Is Moral Consistency Convincing?

```{r}
### Examine pair data

mft_pair <- countMFT(data_pair$pos_text, dict) - countMFT(data_pair$neg_text, dict)

checkTerm <- function(x, return_data = FALSE){
  cases <- c(map(x, grep, data_pair$op_text), map(x, grep, data_pair$op_title)) %>% 
               unlist() %>% unique() %>% sort()
  
  plot_df <- mft_pair[cases,] %>% 
    gather() %>%
    mutate(key = factor(key, levels = rev(c("Authority", "Ingroup", "Purity", "Fairness", "Harm"
                                            , "MFTcombined", "MoralityGeneral"))
                        , labels = rev(c("Authority", "Ingroup", "Purity", "Fairness", "Harm"
                                         , "Foundations\nCombined", "General\nMorality")))) %>%
    group_by(key) %>%
    summarise(mean = mean(value), sd = sd(value), n = n()) %>%
    mutate(se = sd/sqrt(n), cilo = mean - se, cihi = mean + se)
  
  if(return_data) return(plot_df)
  
  xlim <- max(abs(c(plot_df$cilo,plot_df$cihi)))
  xlim <- c(-xlim,xlim)
  
  ggplot(plot_df, aes(y=key, x=mean, xmin=cilo, xmax=cihi)) + 
    theme_classic() + theme(panel.border = element_rect(fill=NA)) +
    geom_point() + geom_errorbarh(height=0) + geom_vline(xintercept = 0) +
    labs(title = paste0("Search Query (",length(cases)," hits):"), subtitle = paste(x, collapse="; ")
         , x = NULL, y = "Moral Foundation") +
    scale_x_continuous(limits=xlim, breaks=.9*xlim, labels = c("Less Persuasive", "More Persuasive")) +
    theme(axis.ticks.x=element_blank())
}

mftTerms <- function(x){
  map(x, grep, names(dict)) %>% 
    unlist() %>% unique %>% sort() %>%
    map(~gsub("*","", dict[[.]], fixed=T)) %>%
    unlist()
}
```

_Authority_

```{r}
checkTerm(mftTerms("AuthorityVirtue"))
```

```{r}
checkTerm(mftTerms("AuthorityVice"))
```

_Ingroup_

```{r}
checkTerm(mftTerms("IngroupVirtue"))
```

```{r}
checkTerm(mftTerms("IngroupVice"))
```

_Purity_

```{r}
checkTerm(mftTerms("PurityVirtue"))
```

```{r}
checkTerm(mftTerms("PurityVice"))
```

_Harm_

```{r}
checkTerm(mftTerms("HarmVirtue"))
```

```{r}
checkTerm(mftTerms("HarmVice"))
```

_Fairness_

```{r}
checkTerm(mftTerms("FairnessVirtue"))
```

```{r}
checkTerm(mftTerms("FairnessVice"))
```


# How about other topics?

```{r}
checkTerm("")
```

```{r}
checkTerm("politic")
```

```{r}
checkTerm(c("liberal","conservati"))
```

```{r}
checkTerm(c("democrat","republican"))
```

```{r}
checkTerm("climate")
```

```{r}
checkTerm(c("climate change","global warming"))
```

```{r}
checkTerm(c("politic","liberal","conservati","democrat","republican","president"
            ,"climate change","global warming"))
```

